config/routes.rb
Rails.application.routes.draw do
  resources :phrases
  resources :boards
  post 'squares/activate', to: 'squares#activate'
  get 'static_pages/index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'static_pages#index'
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :squares, dependent: :delete_all
  
  after_create :generate_board

  default_scope { order(updated_at: :desc) }
  
  def generate_board
    i = 0
    phrases = Phrase.order("RANDOM()").limit(25)
    while i <= 24
      square = Square.new(board_id: self.id, phrase_id: phrases[i].id, active: false)
      square.save
      i += 1
    end
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  # GET /boards or /boards.json
  def index
    if user_is_admin?
      @boards = Board.all
    else
      @boards = current_user.boards
    end
    
  end

  # GET /boards/1 or /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
    @user_id = current_user.id
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = Board.new(:user_id => params[:user_id])

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: "Board was successfully updated." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: "Board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:user_id)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
    def squareActive?(square)
        if square.active
            return "active"
        else 
            return
        end
    end
end

app/views/boards/_board.html.erb
<div class="bingo-container">
    <% if @board.squares %>
        <% @board.squares.each do |square| %>
            <div id="square-<%= square.id %>" class="square grid-lines <%= squareActive?(square) %>">
                <span><%= square.phrase.content %></span>
            </div>
        <% end %>
    <% end %>
</div>

app/views/boards/_form.html.erb
<%= form_with(model: board) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
        <% board.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field(:board, :user_id, :value => current_user.id) %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_is_admin? %>
  <h1>All Boards</h1>
<% else %>
  <h1>My Boards</h1>
<% end %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><p>Board #: <%= board.id %></p></td>
        <td><p><%= board.user.name %></p></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Board', boards_path(:user_id => current_user.id), :method => :post %>

app/views/boards/show.html.erb
<%= javascript_pack_tag 'bingo' %>
<p id="notice"><%= notice %></p>
<div class="container">
    <%= render 'board' %>
</div>
<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>